package cat.company.wandervault.domain.usecase

import cat.company.wandervault.domain.model.Trip
import cat.company.wandervault.domain.repository.TripRepository

/**
 * Use-case that persists an AI-generated description (or clears it) for a trip.
 *
 * @param description The description text to save, or `null` to clear it.
 * @param sourceDocumentId The ID of the document from which the description was extracted,
 *   or `null` to clear the link or when the description is generated by on-device AI.
 */
class SaveTripDescriptionUseCase(private val repository: TripRepository) {
    suspend operator fun invoke(trip: Trip, description: String?, sourceDocumentId: Int? = null) =
        repository.updateTrip(trip.copy(aiDescription = description, aiDescriptionSourceDocumentId = sourceDocumentId))
}
